### ISSUE TITLE
Hypernode Deploy fails with error "Cannot redeclare twig_cycle()"

### ISSUE THREAD

**Issue by fokkejan-made-by-mouses** [ByteInternet/hypernode-deploy-configuration#43]
When we deploy our Magento 2 application to our environment, we get this error:
> hypernode-deploy build -vvv
Agent pid 45
PHP Fatal error:  Cannot redeclare twig_cycle() (previously declared in /opt/atlassian/pipelines/agent/build/vendor/twig/twig/src/Resources/core.php:19) in phar:///bin/hypernode-deploy/vendor/twig/twig/src/Extension/CoreExtension.php on line 362

This only happens with an existing cache in Bitbucket Pipelines.
So when we clear the cache in Bitbucket, the deploy works fine.
But on the next deploy we get the error of 'twig_cycle()'.

We expect that several versions of twig will be used.
Do you know why this happens and how to fix it?

We are using this version of this module:
`hypernode/deploy-configuration: 3.2.0`

For Bitbucket Pipelines we are using this image: `quay.io/hypernode/deploy:3-php8.2-node18`
The application version is `Magento 2.4.7-p2`
And on the server we have: `Node v18.17.1` and `PHP 8.2`

**Comment by mdubbelman** [comment]
I've got the same issue when deploying a Symfony 7 application using the Hypernode deploy configuration. 
I'm using the docker image hypernode/deploy:3.6.1-php8.2-node18

**Comment by tdgroot** [comment]
Hi, thanks for reporting :).

Can you try setting the environment variable `DEPLOY_AUTOLOAD_PATH=''` in your CI?

**Comment by mdubbelman** [comment]
@tdgroot this solution works for me! Thanks!

**Comment by fokkejan-made-by-mouses** [comment]
@tdgroot Yes, it worked for me too. Thx!
I will close this issue.
